ORG 0000h
		MOV A,#45 	; MY ROLL NUMBER IN DECIMAL
		MOV B,#10	
		DIV AB		; DIVIDE BY TEN TO GET TEN'S DIGIT AND UNIT DIGIT
		ADD A,#48	; ADD 48d TO GET ASCII VALUE
		MOV R0,A	; ASCII VALUE OF TEN'S DIGIT IN R0
		MOV A,B		; COPY REMAINDER INTO A
		ADD A,#48	
		MOV R1,A	; ASCII VALUE OF UNIT DIGIT IN R1		
END