ORG 0000h
		MOV 20H,#56h	; 1ST NUMBER IN LOCATION 20H
		MOV 21H,#23h	; 2ND NUMBER IN LOCATION 21H
		MOV A,20H	; MOVE 1ST NUMBER INTO A
		MOV B,21H	; MOVE 2ND NUMBER INTO B
		MUL AB		; MULTIPLY TWO NUMBERS
		MOV 23H,A	; LOWER BYTE OF RESULT IN LOCATION 23H
		MOV 22H,B	; UPPER BYTE OF RESULT IN LOCATION 22H
END
